version: '3'

services:
  app:
    build: .
    command: "python3 run.py"
    ports:
    - "8000:8000"
    links:
    - redis
    - celery
    - db
    volumes:
      - .:/usr/src/app:ro

  celery:
    build: .
    command: "celery -A utils.celery.celery.celery worker"
    volumes:
    - .:/usr/src/app:ro
    links:
    - redis


  redis:
    image: redis:4.0.5-alpine
    ports:
    - "6379:6379"

  db:
    image: postgres:10
    env_file: .env
    ports:
    - "5432:5432"
