version: '3'

services:
  app:
    build: .
    ports:
    - "8000:8000"
    links:
    - redis
    - celery
    volumes:
    - .:/usr/src/app:ro

  celery:
    image: celery
    command: celery -A utils.celery.celery.celery worker
    links:
    - redis
    volumes:
    - .:/usr/src/app:ro

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server"]
    ports:
    - "6379:6379"
